<a href="https://colab.research.google.com/github/Michalinh0/DS2022/blob/main/Classification/Covertype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set up

Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import pandas as pd
import numpy as np
import seaborn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

Prepare dataset

In [2]:
covertype_dataset = pd.read_csv("https://raw.githubusercontent.com/Michalinh0/DS2022/main/Classification/sources/covtype.data")

strOfNames = ["Elevation" , "Aspect" , "Slope" , "Horizontal_Distance_To_Hydrology" , "Vertical_Distance_To_Hydrology" , "Horizontal_Distance_To_Roadways" , "Hillshade_9am" , "Hillshade_Noon" , "Hillshade_3pm" , "Horizontal_Distance_To_Fire_Points"]
for i in range(4):
  strOfNames.append("Wilderness_Area" + str(i+1))
for i in range(40):
  strOfNames.append("Soil_type" + str(i+1))
strOfNames.append("Cover_type")

covertype_dataset.columns = strOfNames

In [3]:
input_vector = strOfNames[0:54]
print(input_vector)

['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4', 'Soil_type1', 'Soil_type2', 'Soil_type3', 'Soil_type4', 'Soil_type5', 'Soil_type6', 'Soil_type7', 'Soil_type8', 'Soil_type9', 'Soil_type10', 'Soil_type11', 'Soil_type12', 'Soil_type13', 'Soil_type14', 'Soil_type15', 'Soil_type16', 'Soil_type17', 'Soil_type18', 'Soil_type19', 'Soil_type20', 'Soil_type21', 'Soil_type22', 'Soil_type23', 'Soil_type24', 'Soil_type25', 'Soil_type26', 'Soil_type27', 'Soil_type28', 'Soil_type29', 'Soil_type30', 'Soil_type31', 'Soil_type32', 'Soil_type33', 'Soil_type34', 'Soil_type35', 'Soil_type36', 'Soil_type37', 'Soil_type38', 'Soil_type39', 'Soil_type40']


In [25]:
#plot = plt.scatter(,covertype_dataset["Elevation"])
covertype_dataset.describe()
#seaborn.displot(covertype_dataset , x = "Elevation")
#seaborn.displot(covertype_dataset , x = "Aspect")
#seaborn.displot(covertype_dataset , x = "Slope")
#seaborn.displot(covertype_dataset , x = "Horizontal_Distance_To_Hydrology")
#seaborn.displot(covertype_dataset , x = "Vertical_Distance_To_Hydrology")
#seaborn.displot(covertype_dataset , x = "Horizontal_Distance_To_Roadways")
#seaborn.displot(covertype_dataset , x = "Hillshade_9am")
#seaborn.displot(covertype_dataset , x = "Hillshade_Noon")
#seaborn.displot(covertype_dataset , x = "Hillshade_3pm")
#seaborn.displot(covertype_dataset , x = "Horizontal_Distance_To_Fire_Points")

Elevation         Aspect          Slope  \
count  581011.000000  581011.000000  581011.000000   
mean     2959.365926     155.656988      14.103723   
std       279.984569     111.913733       7.488234   
min      1859.000000       0.000000       0.000000   
25%      2809.000000      58.000000       9.000000   
50%      2996.000000     127.000000      13.000000   
75%      3163.000000     260.000000      18.000000   
max      3858.000000     360.000000      66.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                     581011.000000                   581011.000000   
mean                         269.428236                       46.418935   
std                          212.549538                       58.295250   
min                            0.000000                     -173.000000   
25%                          108.000000                        7.000000   
50%                          218.000000                       30.000000   
75%                          384.000000                       69.000000   
max                         1397.000000                      601.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                    581011.000000  581011.000000   581011.000000   
mean                       2350.149779     212.146033      223.318701   
std                        1559.254343      26.769909       19.768711   
min                           0.000000       0.000000        0.000000   
25%                        1106.000000     198.000000      213.000000   
50%                        1997.000000     218.000000      226.000000   
75%                        3328.000000     231.000000      237.000000   
max                        7117.000000     254.000000      254.000000   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points  ...    Soil_type32  \
count  581011.000000                       581011.000000  ...  581011.000000   
mean      142.528253                         1980.283828  ...       0.090392   
std        38.274561                         1324.184340  ...       0.286743   
min         0.000000                            0.000000  ...       0.000000   
25%       119.000000                         1024.000000  ...       0.000000   
50%       143.000000                         1710.000000  ...       0.000000   
75%       168.000000                         2550.000000  ...       0.000000   
max       254.000000                         7173.000000  ...       1.000000   

         Soil_type33    Soil_type34    Soil_type35    Soil_type36  \
count  581011.000000  581011.000000  581011.000000  581011.000000   
mean        0.077716       0.002773       0.003255       0.000205   
std         0.267725       0.052584       0.056957       0.014310   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

         Soil_type37    Soil_type38    Soil_type39    Soil_type40  \
count  581011.000000  581011.000000  581011.000000  581011.000000   
mean        0.000513       0.026803       0.023762       0.015060   
std         0.022641       0.161508       0.152307       0.121792   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

          Cover_type  
count  581011.000000  
mean        2.051465  
std         1.396500  
min         1.000000  
25%         1.000000  
50%         2.000000  
75%         2.000000  
max         7.000000  

[8 rows x 55 colu

First model : no data manipulation

In [4]:
x = covertype_dataset[input_vector]
y = covertype_dataset["Cover_type"]

x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size = 0.1)

y_test.value_counts()


2    28400
1    21284
3     3499
7     2011
6     1710
5      957
4      241
Name: Cover_type, dtype: int64

In [5]:
model = LogisticRegression()
model.fit(x_train , y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [6]:
y_pred = model.predict(x_test)

metrics.confusion_matrix(y_test, y_pred)
print(metrics.classification_report(y_test, y_pred, digits=3))


              precision    recall  f1-score   support

           1      0.620     0.643     0.631     21284
           2      0.625     0.770     0.690     28400
           3      0.584     0.167     0.259      3499
           4      0.000     0.000     0.000       241
           5      0.000     0.000     0.000       957
           6      0.000     0.000     0.000      1710
           7      0.000     0.000     0.000      2011

    accuracy                          0.622     58102
   macro avg      0.261     0.226     0.226     58102
weighted avg      0.568     0.622     0.584     58102



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Data normalization

In [7]:
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

Second model - normalized data


In [9]:
x_train ,x_test , y_train , y_test = train_test_split(x_scaled,y,test_size = 0.1)
model = LogisticRegression(solver='liblinear' , verbose = 10)
model.fit(x_train , y_train)

[LibLinear]

LogisticRegression(solver='liblinear', verbose=10)

In [12]:
y_pred = model.predict(x_test)

print (metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred, digits=3))

[[14568  6197    24     0     3     0   434]
 [ 4856 22646   630     0    30    46    48]
 [    0   382  3121    31     2    90     0]
 [    0     0   178    66     0    28     0]
 [   14   858    85     0    13     0     0]
 [    0   624   984     8     2   109     0]
 [  896    10     4     0     0     0  1115]]
              precision    recall  f1-score   support

           1      0.716     0.686     0.701     21226
           2      0.737     0.801     0.768     28256
           3      0.621     0.861     0.721      3626
           4      0.629     0.243     0.350       272
           5      0.260     0.013     0.025       970
           6      0.399     0.063     0.109      1727
           7      0.698     0.551     0.616      2025

    accuracy                          0.717     58102
   macro avg      0.580     0.460     0.470     58102
weighted avg      0.703     0.717     0.701     58102

