<a href="https://colab.research.google.com/github/Michalinh0/DS2022/blob/main/Classification/Covertype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set up

Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import pandas as pd
import numpy as np
import seaborn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

Prepare dataset

In [2]:
covertype_dataset = pd.read_csv("https://raw.githubusercontent.com/Michalinh0/DS2022/main/Classification/sources/covtype.data")

strOfNames = ["Elevation" , "Aspect" , "Slope" , "Horizontal_Distance_To_Hydrology" , "Vertical_Distance_To_Hydrology" , "Horizontal_Distance_To_Roadways" , "Hillshade_9am" , "Hillshade_Noon" , "Hillshade_3pm" , "Horizontal_Distance_To_Fire_Points"]
for i in range(4):
  strOfNames.append("Wilderness_Area" + str(i+1))
for i in range(40):
  strOfNames.append("Soil_type" + str(i+1))
strOfNames.append("Cover_type")

covertype_dataset.columns = strOfNames

In [3]:
input_vector = strOfNames[0:54]
print(input_vector)

['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4', 'Soil_type1', 'Soil_type2', 'Soil_type3', 'Soil_type4', 'Soil_type5', 'Soil_type6', 'Soil_type7', 'Soil_type8', 'Soil_type9', 'Soil_type10', 'Soil_type11', 'Soil_type12', 'Soil_type13', 'Soil_type14', 'Soil_type15', 'Soil_type16', 'Soil_type17', 'Soil_type18', 'Soil_type19', 'Soil_type20', 'Soil_type21', 'Soil_type22', 'Soil_type23', 'Soil_type24', 'Soil_type25', 'Soil_type26', 'Soil_type27', 'Soil_type28', 'Soil_type29', 'Soil_type30', 'Soil_type31', 'Soil_type32', 'Soil_type33', 'Soil_type34', 'Soil_type35', 'Soil_type36', 'Soil_type37', 'Soil_type38', 'Soil_type39', 'Soil_type40']


In [13]:
#plot = plt.scatter(,covertype_dataset["Elevation"])
covertype_dataset.describe()
#seaborn.displot(covertype_dataset , x = "Elevation")
#seaborn.displot(covertype_dataset , x = "Aspect")
#seaborn.displot(covertype_dataset , x = "Slope")
#seaborn.displot(covertype_dataset , x = "Horizontal_Distance_To_Hydrology")
#seaborn.displot(covertype_dataset , x = "Vertical_Distance_To_Hydrology")
#seaborn.displot(covertype_dataset , x = "Horizontal_Distance_To_Roadways")
#seaborn.displot(covertype_dataset , x = "Hillshade_9am")
#seaborn.displot(covertype_dataset , x = "Hillshade_Noon")
#seaborn.displot(covertype_dataset , x = "Hillshade_3pm")
#seaborn.displot(covertype_dataset , x = "Horizontal_Distance_To_Fire_Points")
covertype_dataset["Cover_type"].value_counts()

2    283301
1    211840
3     35754
7     20510
6     17367
5      9492
4      2747
Name: Cover_type, dtype: int64

First model : no data manipulation

In [14]:
x = covertype_dataset[input_vector]
y = covertype_dataset["Cover_type"]

x_train ,x_test , y_train , y_test = train_test_split(x,y,test_size = 0.1)

y_test.value_counts()




2    28255
1    21202
3     3501
7     2050
6     1807
5     1008
4      279
Name: Cover_type, dtype: int64

In [16]:
model = LogisticRegression(class_weight = 'balanced' , solver='liblinear')
model.fit(x_train , y_train)

LogisticRegression(class_weight='balanced', solver='liblinear')

In [17]:
y_pred = model.predict(x_test)

metrics.confusion_matrix(y_test, y_pred)
print(metrics.classification_report(y_test, y_pred, digits=3))


              precision    recall  f1-score   support

           1      0.693     0.663     0.678     21202
           2      0.756     0.692     0.723     28255
           3      0.632     0.717     0.672      3501
           4      0.361     0.616     0.455       279
           5      0.188     0.422     0.260      1008
           6      0.344     0.474     0.399      1807
           7      0.546     0.724     0.623      2050

    accuracy                          0.672     58102
   macro avg      0.503     0.616     0.544     58102
weighted avg      0.693     0.672     0.680     58102



Data normalization

In [30]:
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
print(x_scaled)
df = pd.DataFrame(x_scaled)
df.describe()

[[0.36568284 0.15555556 0.03030303 ... 0.         0.         0.        ]
 [0.47273637 0.38611111 0.13636364 ... 0.         0.         0.        ]
 [0.46323162 0.43055556 0.27272727 ... 0.         0.         0.        ]
 ...
 [0.26363182 0.44166667 0.25757576 ... 0.         0.         0.        ]
 [0.26263132 0.47222222 0.22727273 ... 0.         0.         0.        ]
 [0.26213107 0.45833333 0.1969697  ... 0.         0.         0.        ]]


0              1              2              3   \
count  581011.000000  581011.000000  581011.000000  581011.000000   
mean        0.550458       0.432381       0.213693       0.192862   
std         0.140062       0.310871       0.113458       0.152147   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.475238       0.161111       0.136364       0.077309   
50%         0.568784       0.352778       0.196970       0.156049   
75%         0.652326       0.722222       0.272727       0.274875   
max         1.000000       1.000000       1.000000       1.000000   

                  4              5              6              7   \
count  581011.000000  581011.000000  581011.000000  581011.000000   
mean        0.283487       0.330216       0.835221       0.879207   
std         0.075317       0.219089       0.105393       0.077830   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.232558       0.155403       0.779528       0.838583   
50%         0.262274       0.280596       0.858268       0.889764   
75%         0.312661       0.467613       0.909449       0.933071   
max         1.000000       1.000000       1.000000       1.000000   

                  8              9   ...             44             45  \
count  581011.000000  581011.000000  ...  581011.000000  581011.000000   
mean        0.561135       0.276075  ...       0.044175       0.090392   
std         0.150687       0.184607  ...       0.205483       0.286743   
min         0.000000       0.000000  ...       0.000000       0.000000   
25%         0.468504       0.142758  ...       0.000000       0.000000   
50%         0.562992       0.238394  ...       0.000000       0.000000   
75%         0.661417       0.355500  ...       0.000000       0.000000   
max         1.000000       1.000000  ...       1.000000       1.000000   

                  46             47             48             49  \
count  581011.000000  581011.000000  581011.000000  581011.000000   
mean        0.077716       0.002773       0.003255       0.000205   
std         0.267725       0.052584       0.056957       0.014310   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

                  50             51             52             53  
count  581011.000000  581011.000000  581011.000000  581011.000000  
mean        0.000513       0.026803       0.023762       0.015060  
std         0.022641       0.161508       0.152307       0.121792  
min         0.000000       0.000000       0.000000       0.000000  
25%         0.000000       0.000000       0.000000       0.000000  
50%         0.000000       0.000000       0.000000       0.000000  
75%         0.000000       0.000000       0.000000       0.000000  
max         1.000000       1.000000       1.000000       1.000000  

[8 rows x 54 columns]

Second model - normalized data


In [19]:
x_train ,x_test , y_train , y_test = train_test_split(x_scaled,y,test_size = 0.1)
model = LogisticRegression(solver='liblinear' , class_weight = 'balanced')
model.fit(x_train , y_train)

[LibLinear]

LogisticRegression(solver='liblinear', verbose=10)

In [20]:
y_pred = model.predict(x_test)

print (metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred, digits=3))

[[14646  6143    19     0     0     0   416]
 [ 4889 22632   664     1    24    39    34]
 [    0   371  3072    23     0    93     0]
 [    0     0   196    69     0    30     0]
 [   12   794    96     0    13     3     0]
 [    0   662  1003     5     2   145     0]
 [  911    12     9     0     0     0  1074]]
              precision    recall  f1-score   support

           1      0.716     0.690     0.703     21224
           2      0.739     0.800     0.769     28283
           3      0.607     0.863     0.713      3559
           4      0.704     0.234     0.351       295
           5      0.333     0.014     0.027       918
           6      0.468     0.080     0.136      1817
           7      0.705     0.535     0.608      2006

    accuracy                          0.717     58102
   macro avg      0.610     0.460     0.472     58102
weighted avg      0.706     0.717     0.702     58102



Third model - target encoding